require:
  - rubocop-performance
  - rubocop-rails

AllCops:
  NewCops: enable
  TargetRubyVersion: 3.3.1
  Exclude:
    - db/**/*
    - vendor/**/*
    - log/**/*
    - tmp/**/*
    - storage/**/*
    - lib/tasks/**/*
    - bin/*

Lint/MissingSuper:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Layout/LineLength:
  Enabled: true
  Max: 120
  Exclude:
    - 'Gemfile'

Metrics/MethodLength:
  CountAsOne: ['array', 'hash']
Metrics/BlockLength:
  CountAsOne: ['array', 'hash']
  Exclude:
    - 'test/**/*'
    - 'config/routes.rb'
Style/Documentation:
  Enabled: false
Style/HashSyntax:
  Enabled: false
